name = "club"
compatibility_date = "2024-11-01" # Өнөөдрийн байдлаар хамгийн тогтвортой огноо
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output"

[[d1_databases]]
binding = "DB" 
database_name = "platform-db"
database_id = "fae5657e-b3e6-441e-be50-877e1482bb2e"