
name = "club"
compatibility_date = "2026-02-05"
compatibility_flags = ["nodejs_compat"]
[[d1_databases]]
binding = "DB"
database_name = "platform-db"
database_id = "fae5657e-b3e6-441e-be50-877e1482bb2e"